# Test your FastAPI endpoints

POST http://172.19.160.123:8000/svc_id/get
Accept: application/json
Content-Type: application/json

{
    "game_id": 1,
    "area_id": 2,
    "count": 10
}


###

POST http://127.0.0.1:8000/svc_id/recycle
Accept: application/json
Content-Type: application/json

{
"game_id": 1,
"area_id": 2
}



###

POST http://127.0.0.1:8000/svc_id/resize
Accept: application/json
Content-Type: application/json

{
  "game_id": 1,
  "area_id": 2,
  "resize": 8
}
